name: Arcade 3.0 Cross-Platform Tests

on: [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.12']
    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up environment
      run: |
        sudo apt-get update
        sudo apt-get install -y libglfw3-dev libgles2-mesa-dev

    - name: Install dependencies
      run: |
        make setup
        uv python pin ${{ matrix.python-version }}
        uv add pytest pytest-cov --dev
        uv sync --all-extras --dev
    
    - name: Run tests
      run: |
        uv run pytest tests/ --show-capture=no